# Generated by Django 2.2.7 on 2019-11-19 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_debtor_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
