# Generated by Django 2.2.7 on 2019-11-19 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191119_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='last_email_sent',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
