# Generated by Django 2.2.7 on 2019-11-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0004_debtor_last_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
