# Generated by Django 2.2.7 on 2019-11-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_debtor_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='last_email_sent',
            field=models.DateField(blank=True),
        ),
    ]
