# Generated by Django 2.2.7 on 2019-11-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191120_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='image',
            field=models.ImageField(default='default.jpg', height_field=300, upload_to='debtor_pics', width_field=300),
        ),
    ]
