# Generated by Django 2.2.7 on 2019-11-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_debtor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='image',
        ),
    ]
