# Generated by Django 2.2.7 on 2019-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_debtor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='debtor_pics'),
        ),
    ]
